# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlserver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emlserver.proto\"\x16\n\x07Message\x12\x0b\n\x03Msg\x18\x01 \x01(\t\")\n\tMsgSample\x12\r\n\x05XData\x18\x01 \x01(\x0c\x12\r\n\x05YData\x18\x02 \x01(\x03\"\x19\n\tMsgPredIn\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\x0c\"3\n\nMsgPredOut\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\x0c\x12\x17\n\x03\x45rr\x18\x02 \x01(\x0e\x32\n.EnumError\"\x1d\n\x07MsgInit\x12\x12\n\nSampleSize\x18\x01 \x01(\x03\"#\n\x08MsgError\x12\x17\n\x03\x45rr\x18\x01 \x01(\x0e\x32\n.EnumError\"\t\n\x07VoidMsg*;\n\tEnumError\x12\x15\n\x11\x45NUMERROR_NOERROR\x10\x00\x12\x17\n\x13\x45NUMERROR_NOOUTDATA\x10\x01\x32\xf3\x01\n\x08Messager\x12\x1c\n\x04Test\x12\x08.VoidMsg\x1a\x08.VoidMsg\"\x00\x12/\n\x14\x41ppendTrainingSample\x12\n.MsgSample\x1a\t.MsgError\"\x00\x12%\n\x0cInitMlParams\x12\x08.MsgInit\x1a\t.MsgError\"\x00\x12\x1d\n\x05Train\x12\x08.VoidMsg\x1a\x08.VoidMsg\"\x00\x12.\n\x13\x41ppendPredictSample\x12\n.MsgPredIn\x1a\t.MsgError\"\x00\x12\"\n\x07Predict\x12\x08.VoidMsg\x1a\x0b.MsgPredOut\"\x00\x42\nZ\x08./protosb\x06proto3')

_ENUMERROR = DESCRIPTOR.enum_types_by_name['EnumError']
EnumError = enum_type_wrapper.EnumTypeWrapper(_ENUMERROR)
ENUMERROR_NOERROR = 0
ENUMERROR_NOOUTDATA = 1


_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
_MSGSAMPLE = DESCRIPTOR.message_types_by_name['MsgSample']
_MSGPREDIN = DESCRIPTOR.message_types_by_name['MsgPredIn']
_MSGPREDOUT = DESCRIPTOR.message_types_by_name['MsgPredOut']
_MSGINIT = DESCRIPTOR.message_types_by_name['MsgInit']
_MSGERROR = DESCRIPTOR.message_types_by_name['MsgError']
_VOIDMSG = DESCRIPTOR.message_types_by_name['VoidMsg']
Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'mlserver_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

MsgSample = _reflection.GeneratedProtocolMessageType('MsgSample', (_message.Message,), {
  'DESCRIPTOR' : _MSGSAMPLE,
  '__module__' : 'mlserver_pb2'
  # @@protoc_insertion_point(class_scope:MsgSample)
  })
_sym_db.RegisterMessage(MsgSample)

MsgPredIn = _reflection.GeneratedProtocolMessageType('MsgPredIn', (_message.Message,), {
  'DESCRIPTOR' : _MSGPREDIN,
  '__module__' : 'mlserver_pb2'
  # @@protoc_insertion_point(class_scope:MsgPredIn)
  })
_sym_db.RegisterMessage(MsgPredIn)

MsgPredOut = _reflection.GeneratedProtocolMessageType('MsgPredOut', (_message.Message,), {
  'DESCRIPTOR' : _MSGPREDOUT,
  '__module__' : 'mlserver_pb2'
  # @@protoc_insertion_point(class_scope:MsgPredOut)
  })
_sym_db.RegisterMessage(MsgPredOut)

MsgInit = _reflection.GeneratedProtocolMessageType('MsgInit', (_message.Message,), {
  'DESCRIPTOR' : _MSGINIT,
  '__module__' : 'mlserver_pb2'
  # @@protoc_insertion_point(class_scope:MsgInit)
  })
_sym_db.RegisterMessage(MsgInit)

MsgError = _reflection.GeneratedProtocolMessageType('MsgError', (_message.Message,), {
  'DESCRIPTOR' : _MSGERROR,
  '__module__' : 'mlserver_pb2'
  # @@protoc_insertion_point(class_scope:MsgError)
  })
_sym_db.RegisterMessage(MsgError)

VoidMsg = _reflection.GeneratedProtocolMessageType('VoidMsg', (_message.Message,), {
  'DESCRIPTOR' : _VOIDMSG,
  '__module__' : 'mlserver_pb2'
  # @@protoc_insertion_point(class_scope:VoidMsg)
  })
_sym_db.RegisterMessage(VoidMsg)

_MESSAGER = DESCRIPTOR.services_by_name['Messager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./protos'
  _ENUMERROR._serialized_start=244
  _ENUMERROR._serialized_end=303
  _MESSAGE._serialized_start=18
  _MESSAGE._serialized_end=40
  _MSGSAMPLE._serialized_start=42
  _MSGSAMPLE._serialized_end=83
  _MSGPREDIN._serialized_start=85
  _MSGPREDIN._serialized_end=110
  _MSGPREDOUT._serialized_start=112
  _MSGPREDOUT._serialized_end=163
  _MSGINIT._serialized_start=165
  _MSGINIT._serialized_end=194
  _MSGERROR._serialized_start=196
  _MSGERROR._serialized_end=231
  _VOIDMSG._serialized_start=233
  _VOIDMSG._serialized_end=242
  _MESSAGER._serialized_start=306
  _MESSAGER._serialized_end=549
# @@protoc_insertion_point(module_scope)
