// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: mlserver.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumError int32

const (
	EnumError_ENUMERROR_NOERROR   EnumError = 0
	EnumError_ENUMERROR_NOOUTDATA EnumError = 1
)

// Enum value maps for EnumError.
var (
	EnumError_name = map[int32]string{
		0: "ENUMERROR_NOERROR",
		1: "ENUMERROR_NOOUTDATA",
	}
	EnumError_value = map[string]int32{
		"ENUMERROR_NOERROR":   0,
		"ENUMERROR_NOOUTDATA": 1,
	}
)

func (x EnumError) Enum() *EnumError {
	p := new(EnumError)
	*p = x
	return p
}

func (x EnumError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumError) Descriptor() protoreflect.EnumDescriptor {
	return file_mlserver_proto_enumTypes[0].Descriptor()
}

func (EnumError) Type() protoreflect.EnumType {
	return &file_mlserver_proto_enumTypes[0]
}

func (x EnumError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumError.Descriptor instead.
func (EnumError) EnumDescriptor() ([]byte, []int) {
	return file_mlserver_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mlserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_mlserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_mlserver_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MsgSample struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XData []byte `protobuf:"bytes,1,opt,name=XData,proto3" json:"XData,omitempty"`
	YData int64  `protobuf:"varint,2,opt,name=YData,proto3" json:"YData,omitempty"`
}

func (x *MsgSample) Reset() {
	*x = MsgSample{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mlserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSample) ProtoMessage() {}

func (x *MsgSample) ProtoReflect() protoreflect.Message {
	mi := &file_mlserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSample.ProtoReflect.Descriptor instead.
func (*MsgSample) Descriptor() ([]byte, []int) {
	return file_mlserver_proto_rawDescGZIP(), []int{1}
}

func (x *MsgSample) GetXData() []byte {
	if x != nil {
		return x.XData
	}
	return nil
}

func (x *MsgSample) GetYData() int64 {
	if x != nil {
		return x.YData
	}
	return 0
}

type MsgPredIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *MsgPredIn) Reset() {
	*x = MsgPredIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mlserver_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPredIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPredIn) ProtoMessage() {}

func (x *MsgPredIn) ProtoReflect() protoreflect.Message {
	mi := &file_mlserver_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPredIn.ProtoReflect.Descriptor instead.
func (*MsgPredIn) Descriptor() ([]byte, []int) {
	return file_mlserver_proto_rawDescGZIP(), []int{2}
}

func (x *MsgPredIn) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type MsgPredOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte    `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Err  EnumError `protobuf:"varint,2,opt,name=Err,proto3,enum=EnumError" json:"Err,omitempty"`
}

func (x *MsgPredOut) Reset() {
	*x = MsgPredOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mlserver_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPredOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPredOut) ProtoMessage() {}

func (x *MsgPredOut) ProtoReflect() protoreflect.Message {
	mi := &file_mlserver_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPredOut.ProtoReflect.Descriptor instead.
func (*MsgPredOut) Descriptor() ([]byte, []int) {
	return file_mlserver_proto_rawDescGZIP(), []int{3}
}

func (x *MsgPredOut) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MsgPredOut) GetErr() EnumError {
	if x != nil {
		return x.Err
	}
	return EnumError_ENUMERROR_NOERROR
}

type MsgInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SampleSize int64 `protobuf:"varint,1,opt,name=SampleSize,proto3" json:"SampleSize,omitempty"`
}

func (x *MsgInit) Reset() {
	*x = MsgInit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mlserver_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgInit) ProtoMessage() {}

func (x *MsgInit) ProtoReflect() protoreflect.Message {
	mi := &file_mlserver_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgInit.ProtoReflect.Descriptor instead.
func (*MsgInit) Descriptor() ([]byte, []int) {
	return file_mlserver_proto_rawDescGZIP(), []int{4}
}

func (x *MsgInit) GetSampleSize() int64 {
	if x != nil {
		return x.SampleSize
	}
	return 0
}

type MsgError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err EnumError `protobuf:"varint,1,opt,name=Err,proto3,enum=EnumError" json:"Err,omitempty"`
}

func (x *MsgError) Reset() {
	*x = MsgError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mlserver_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgError) ProtoMessage() {}

func (x *MsgError) ProtoReflect() protoreflect.Message {
	mi := &file_mlserver_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgError.ProtoReflect.Descriptor instead.
func (*MsgError) Descriptor() ([]byte, []int) {
	return file_mlserver_proto_rawDescGZIP(), []int{5}
}

func (x *MsgError) GetErr() EnumError {
	if x != nil {
		return x.Err
	}
	return EnumError_ENUMERROR_NOERROR
}

type VoidMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VoidMsg) Reset() {
	*x = VoidMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mlserver_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoidMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidMsg) ProtoMessage() {}

func (x *VoidMsg) ProtoReflect() protoreflect.Message {
	mi := &file_mlserver_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidMsg.ProtoReflect.Descriptor instead.
func (*VoidMsg) Descriptor() ([]byte, []int) {
	return file_mlserver_proto_rawDescGZIP(), []int{6}
}

var File_mlserver_proto protoreflect.FileDescriptor

var file_mlserver_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x6c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x1b, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x37, 0x0a,
	0x09, 0x4d, 0x73, 0x67, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x58, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x58, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x14, 0x0a, 0x05, 0x59, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x59, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1f, 0x0a, 0x09, 0x4d, 0x73, 0x67, 0x50, 0x72, 0x65,
	0x64, 0x49, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x0a, 0x4d, 0x73, 0x67, 0x50, 0x72,
	0x65, 0x64, 0x4f, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x03, 0x45, 0x72, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x52, 0x03, 0x45, 0x72, 0x72, 0x22, 0x29, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x49, 0x6e,
	0x69, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x22, 0x28, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c,
	0x0a, 0x03, 0x45, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x45, 0x6e,
	0x75, 0x6d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x03, 0x45, 0x72, 0x72, 0x22, 0x09, 0x0a, 0x07,
	0x56, 0x6f, 0x69, 0x64, 0x4d, 0x73, 0x67, 0x2a, 0x3b, 0x0a, 0x09, 0x45, 0x6e, 0x75, 0x6d, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x4e, 0x55, 0x4d, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x5f, 0x4e, 0x4f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x45,
	0x4e, 0x55, 0x4d, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x4e, 0x4f, 0x4f, 0x55, 0x54, 0x44, 0x41,
	0x54, 0x41, 0x10, 0x01, 0x32, 0xf3, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x08, 0x2e, 0x56, 0x6f, 0x69, 0x64,
	0x4d, 0x73, 0x67, 0x1a, 0x08, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12,
	0x2f, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x0a, 0x2e, 0x4d, 0x73, 0x67, 0x53, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x1a, 0x09, 0x2e, 0x4d, 0x73, 0x67, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00,
	0x12, 0x25, 0x0a, 0x0c, 0x49, 0x6e, 0x69, 0x74, 0x4d, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x08, 0x2e, 0x4d, 0x73, 0x67, 0x49, 0x6e, 0x69, 0x74, 0x1a, 0x09, 0x2e, 0x4d, 0x73, 0x67,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x1d, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x69, 0x6e,
	0x12, 0x08, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x4d, 0x73, 0x67, 0x1a, 0x08, 0x2e, 0x56, 0x6f, 0x69,
	0x64, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64,
	0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x0a, 0x2e,
	0x4d, 0x73, 0x67, 0x50, 0x72, 0x65, 0x64, 0x49, 0x6e, 0x1a, 0x09, 0x2e, 0x4d, 0x73, 0x67, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x74, 0x12, 0x08, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x4d, 0x73, 0x67, 0x1a, 0x0b, 0x2e, 0x4d, 0x73,
	0x67, 0x50, 0x72, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mlserver_proto_rawDescOnce sync.Once
	file_mlserver_proto_rawDescData = file_mlserver_proto_rawDesc
)

func file_mlserver_proto_rawDescGZIP() []byte {
	file_mlserver_proto_rawDescOnce.Do(func() {
		file_mlserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_mlserver_proto_rawDescData)
	})
	return file_mlserver_proto_rawDescData
}

var file_mlserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mlserver_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mlserver_proto_goTypes = []interface{}{
	(EnumError)(0),     // 0: EnumError
	(*Message)(nil),    // 1: Message
	(*MsgSample)(nil),  // 2: MsgSample
	(*MsgPredIn)(nil),  // 3: MsgPredIn
	(*MsgPredOut)(nil), // 4: MsgPredOut
	(*MsgInit)(nil),    // 5: MsgInit
	(*MsgError)(nil),   // 6: MsgError
	(*VoidMsg)(nil),    // 7: VoidMsg
}
var file_mlserver_proto_depIdxs = []int32{
	0, // 0: MsgPredOut.Err:type_name -> EnumError
	0, // 1: MsgError.Err:type_name -> EnumError
	7, // 2: Messager.Test:input_type -> VoidMsg
	2, // 3: Messager.AppendTrainingSample:input_type -> MsgSample
	5, // 4: Messager.InitMlParams:input_type -> MsgInit
	7, // 5: Messager.Train:input_type -> VoidMsg
	3, // 6: Messager.AppendPredictSample:input_type -> MsgPredIn
	7, // 7: Messager.Predict:input_type -> VoidMsg
	7, // 8: Messager.Test:output_type -> VoidMsg
	6, // 9: Messager.AppendTrainingSample:output_type -> MsgError
	6, // 10: Messager.InitMlParams:output_type -> MsgError
	7, // 11: Messager.Train:output_type -> VoidMsg
	6, // 12: Messager.AppendPredictSample:output_type -> MsgError
	4, // 13: Messager.Predict:output_type -> MsgPredOut
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mlserver_proto_init() }
func file_mlserver_proto_init() {
	if File_mlserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mlserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mlserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgSample); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mlserver_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPredIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mlserver_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPredOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mlserver_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgInit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mlserver_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mlserver_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoidMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mlserver_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mlserver_proto_goTypes,
		DependencyIndexes: file_mlserver_proto_depIdxs,
		EnumInfos:         file_mlserver_proto_enumTypes,
		MessageInfos:      file_mlserver_proto_msgTypes,
	}.Build()
	File_mlserver_proto = out.File
	file_mlserver_proto_rawDesc = nil
	file_mlserver_proto_goTypes = nil
	file_mlserver_proto_depIdxs = nil
}
