// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: mlserver.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MessagerClient is the client API for Messager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessagerClient interface {
	Test(ctx context.Context, in *VoidMsg, opts ...grpc.CallOption) (*VoidMsg, error)
	AppendTrainingSample(ctx context.Context, in *MsgSample, opts ...grpc.CallOption) (*MsgError, error)
	InitMlParams(ctx context.Context, in *MsgInit, opts ...grpc.CallOption) (*MsgError, error)
	Train(ctx context.Context, in *VoidMsg, opts ...grpc.CallOption) (*VoidMsg, error)
	AppendPredictSample(ctx context.Context, in *MsgPredIn, opts ...grpc.CallOption) (*MsgError, error)
	Predict(ctx context.Context, in *VoidMsg, opts ...grpc.CallOption) (*MsgPredOut, error)
}

type messagerClient struct {
	cc grpc.ClientConnInterface
}

func NewMessagerClient(cc grpc.ClientConnInterface) MessagerClient {
	return &messagerClient{cc}
}

func (c *messagerClient) Test(ctx context.Context, in *VoidMsg, opts ...grpc.CallOption) (*VoidMsg, error) {
	out := new(VoidMsg)
	err := c.cc.Invoke(ctx, "/Messager/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagerClient) AppendTrainingSample(ctx context.Context, in *MsgSample, opts ...grpc.CallOption) (*MsgError, error) {
	out := new(MsgError)
	err := c.cc.Invoke(ctx, "/Messager/AppendTrainingSample", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagerClient) InitMlParams(ctx context.Context, in *MsgInit, opts ...grpc.CallOption) (*MsgError, error) {
	out := new(MsgError)
	err := c.cc.Invoke(ctx, "/Messager/InitMlParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagerClient) Train(ctx context.Context, in *VoidMsg, opts ...grpc.CallOption) (*VoidMsg, error) {
	out := new(VoidMsg)
	err := c.cc.Invoke(ctx, "/Messager/Train", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagerClient) AppendPredictSample(ctx context.Context, in *MsgPredIn, opts ...grpc.CallOption) (*MsgError, error) {
	out := new(MsgError)
	err := c.cc.Invoke(ctx, "/Messager/AppendPredictSample", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messagerClient) Predict(ctx context.Context, in *VoidMsg, opts ...grpc.CallOption) (*MsgPredOut, error) {
	out := new(MsgPredOut)
	err := c.cc.Invoke(ctx, "/Messager/Predict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessagerServer is the server API for Messager service.
// All implementations must embed UnimplementedMessagerServer
// for forward compatibility
type MessagerServer interface {
	Test(context.Context, *VoidMsg) (*VoidMsg, error)
	AppendTrainingSample(context.Context, *MsgSample) (*MsgError, error)
	InitMlParams(context.Context, *MsgInit) (*MsgError, error)
	Train(context.Context, *VoidMsg) (*VoidMsg, error)
	AppendPredictSample(context.Context, *MsgPredIn) (*MsgError, error)
	Predict(context.Context, *VoidMsg) (*MsgPredOut, error)
	mustEmbedUnimplementedMessagerServer()
}

// UnimplementedMessagerServer must be embedded to have forward compatible implementations.
type UnimplementedMessagerServer struct {
}

func (UnimplementedMessagerServer) Test(context.Context, *VoidMsg) (*VoidMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}
func (UnimplementedMessagerServer) AppendTrainingSample(context.Context, *MsgSample) (*MsgError, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendTrainingSample not implemented")
}
func (UnimplementedMessagerServer) InitMlParams(context.Context, *MsgInit) (*MsgError, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitMlParams not implemented")
}
func (UnimplementedMessagerServer) Train(context.Context, *VoidMsg) (*VoidMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Train not implemented")
}
func (UnimplementedMessagerServer) AppendPredictSample(context.Context, *MsgPredIn) (*MsgError, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendPredictSample not implemented")
}
func (UnimplementedMessagerServer) Predict(context.Context, *VoidMsg) (*MsgPredOut, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedMessagerServer) mustEmbedUnimplementedMessagerServer() {}

// UnsafeMessagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessagerServer will
// result in compilation errors.
type UnsafeMessagerServer interface {
	mustEmbedUnimplementedMessagerServer()
}

func RegisterMessagerServer(s grpc.ServiceRegistrar, srv MessagerServer) {
	s.RegisterService(&Messager_ServiceDesc, srv)
}

func _Messager_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagerServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Messager/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagerServer).Test(ctx, req.(*VoidMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messager_AppendTrainingSample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSample)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagerServer).AppendTrainingSample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Messager/AppendTrainingSample",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagerServer).AppendTrainingSample(ctx, req.(*MsgSample))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messager_InitMlParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagerServer).InitMlParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Messager/InitMlParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagerServer).InitMlParams(ctx, req.(*MsgInit))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messager_Train_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagerServer).Train(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Messager/Train",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagerServer).Train(ctx, req.(*VoidMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messager_AppendPredictSample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPredIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagerServer).AppendPredictSample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Messager/AppendPredictSample",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagerServer).AppendPredictSample(ctx, req.(*MsgPredIn))
	}
	return interceptor(ctx, in, info, handler)
}

func _Messager_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagerServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Messager/Predict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagerServer).Predict(ctx, req.(*VoidMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// Messager_ServiceDesc is the grpc.ServiceDesc for Messager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Messager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Messager",
	HandlerType: (*MessagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _Messager_Test_Handler,
		},
		{
			MethodName: "AppendTrainingSample",
			Handler:    _Messager_AppendTrainingSample_Handler,
		},
		{
			MethodName: "InitMlParams",
			Handler:    _Messager_InitMlParams_Handler,
		},
		{
			MethodName: "Train",
			Handler:    _Messager_Train_Handler,
		},
		{
			MethodName: "AppendPredictSample",
			Handler:    _Messager_AppendPredictSample_Handler,
		},
		{
			MethodName: "Predict",
			Handler:    _Messager_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mlserver.proto",
}
